version: '3.9'
services:
  express:
    build:
      context: ./
    ports: 
      - '3000:3000'
    volumes: 
      - .:/docker-sample
      - /docker-sample/node_modules
    command:
      - nodemon 
      - server.js